version: '2'

services:

  mysql:
    container_name: din-db
    image: mysql:8.0
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql:cached
      - ./mysql/conf:/etc/mysql/conf.d:cached
    environment:
      MYSQL_DATABASE: din
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      BIND-ADDRESS: 0.0.0.0

volumes:
  mysql-data:
    driver: local
